- name: Initialisation du serveur
  hosts: cloud1_admin
  remote_user: vburton
  become: yes
  vars:
    user: "{{ lookup('ini', 'ANSIBLE_USER type=properties file=../.env') }}"
  
  roles:
    - role: ../roles/common
      tags: ['common']